<?php

namespace Database\Seeders;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('reviews')->insert([
    [
        'user_id' => 1,
        'book_id' => 12,
        'rating' => 5,
        'comment' => 'Sách rất hay, nội dung sâu sắc và hữu ích.',
        'date_review' => '2024-01-10',
    ],
    [
        'user_id' => 2,
        'book_id' => 33,
        'rating' => 4,
        'comment' => 'Đọc khá thú vị nhưng có vài phần hơi dài dòng.',
        'date_review' => '2024-02-05',
    ],
    [
        'user_id' => 5,
        'book_id' => 7,
        'rating' => 3,
        'comment' => 'Nội dung tạm ổn, không quá xuất sắc.',
        'date_review' => '2024-03-15',
    ],
    [
        'user_id' => 6,
        'book_id' => 21,
        'rating' => 4,
        'comment' => 'Phần minh họa đẹp, giúp hiểu bài dễ dàng hơn.',
        'date_review' => '2024-04-01',
    ],
    [
        'user_id' => 7,
        'book_id' => 5,
        'rating' => 2,
        'comment' => 'Chưa hài lòng lắm, cần cải thiện thêm.',
        'date_review' => '2024-04-20',
    ],
    [
        'user_id' => 8,
        'book_id' => 15,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2024-05-10',
    ],
    [
        'user_id' => 9,
        'book_id' => 30,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, sẽ giới thiệu cho bạn bè.',
        'date_review' => '2024-06-01',
    ],
    [
        'user_id' => 10,
        'book_id' => 18,
        'rating' => 3,
        'comment' => 'Câu chuyện bình thường, không có gì đặc sắc.',
        'date_review' => '2024-06-15',
    ],
    [
        'user_id' => 11,
        'book_id' => 25,
        'rating' => 5,
        'comment' => 'Tác giả đã làm rất tốt, tôi rất thích cách viết của họ.',
        'date_review' => '2024-07-05',
    ],
    [
        'user_id' => 12,
        'book_id' => 3,
        'rating' => 4,
        'comment' => 'Một cuốn sách đáng đọc, nhưng có vài chỗ hơi khó hiểu.',
        'date_review' => '2024-07-20',
    ],
    [
        'user_id' => 13,
        'book_id' => 9,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2024-08-01',
    ],
    [
        'user_id' => 14,
        'book_id' => 14,
        'rating' => 5,
        'comment' => 'Một tác phẩm tuyệt vời, tôi đã học được rất nhiều từ nó.',
        'date_review' => '2024-08-15',
    ],
    [
        'user_id' => 15,
        'book_id' => 20,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2024-09-01',
    ],
    [
        'user_id' => 16,
        'book_id' => 28,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2024-09-20',
    ],
    [
        'user_id' => 17,
        'book_id' => 35,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2024-10-05',
    ],
    [
        'user_id' => 18,
        'book_id' => 2,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2024-10-15',
    ],
    [
        'user_id' => 19,
        'book_id' => 8,
        'rating' => 3,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2024-11-01',
    ],
    [
        'user_id' => 20,
        'book_id' => 13,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2024-11-20',
    ],
    [
        'user_id' => 21,
        'book_id' => 22,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2024-12-01',
    ],
    [
        'user_id' => 22,
        'book_id' => 29,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2024-12-15',
    ],
    [
        'user_id' => 23,
        'book_id' => 34,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2025-01-05',
    ],
    [
        'user_id' => 24,
        'book_id' => 4,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2025-01-20',
    ],
    [
        'user_id' => 25,
        'book_id' => 6,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2025-02-01',
    ],
    [
        'user_id' => 26,
        'book_id' => 10,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2025-02-15',
    ],
    [
        'user_id' => 27,
        'book_id' => 11,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2025-03-01',
    ],
    [
        'user_id' => 28,
        'book_id' => 17,
        'rating' => 3,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2025-03-20',
    ],
    [
        'user_id' => 29,
        'book_id' => 19,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2025-04-05',
    ],
    [
        'user_id' => 30,
        'book_id' => 23,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2025-04-20',
    ],
    [
        'user_id' => 31,
        'book_id' => 24,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2025-05-01',
    ],
    [
        'user_id' => 32,
        'book_id' => 26,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2025-05-15',
    ],
    [
        'user_id' => 33,
        'book_id' => 27,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2025-06-01',
    ],
    [
        'user_id' => 34,
        'book_id' => 31,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2025-06-20',
    ],
    [
        'user_id' => 35,
        'book_id' => 32,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2025-07-05',
    ],
    [
        'user_id' => 36,
        'book_id' => 36,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2025-07-20',
    ],
    [
        'user_id' => 37,
        'book_id' => 37,
        'rating' => 3,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2025-08-01',
    ],
    [
        'user_id' => 38,
        'book_id' => 38,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2025-08-15',
    ],
    [
        'user_id' => 39,
        'book_id' => 39,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2025-09-01',
    ],
    [
        'user_id' => 40,
        'book_id' => 40,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2025-09-20',
    ],
    [
        'user_id' => 41,
        'book_id' => 41,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2025-10-05',
    ],
    [
        'user_id' => 42,
        'book_id' => 42,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2025-10-20',
    ],
    [
        'user_id' => 43,
        'book_id' => 43,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2025-11-01',
    ],
    [
        'user_id' => 44,
        'book_id' => 44,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2025-11-15',
    ],
    [
        'user_id' => 45,
        'book_id' => 45,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2025-12-01',
    ],
    [
        'user_id' => 46,
        'book_id' => 46,
        'rating' => 3,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2025-12-20',
    ],
    [
        'user_id' => 47,
        'book_id' => 47,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2026-01-05',
    ],
    [
        'user_id' => 48,
        'book_id' => 48,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2026-01-20',
    ],
    [
        'user_id' => 49,
        'book_id' => 49,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2026-02-01',
    ],
    [
        'user_id' => 50,
        'book_id' => 50,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2026-02-15',
    ],
    [
        'user_id' => 51,
        'book_id' => 51,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2026-03-01',
    ],
    [
        'user_id' => 52,
        'book_id' => 22,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2026-03-20',
    ],
    [
        'user_id' => 53,
        'book_id' => 13,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2026-04-05',
    ],
    [
        'user_id' => 54,
        'book_id' => 44,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2026-04-20',
    ],
    [
        'user_id' => 55,
        'book_id' => 35,
        'rating' => 2,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2026-05-01',
    ],
    [
        'user_id' => 56,
        'book_id' => 26,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2026-05-15',
    ],
    [
        'user_id' => 57,
        'book_id' => 17,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2026-06-01',
    ],
    [
        'user_id' => 58,
        'book_id' => 8,
        'rating' => 3,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2026-06-20',
    ],
    [
        'user_id' => 59,
        'book_id' => 19,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2026-07-05',
    ],
    [
        'user_id' => 60,
        'book_id' => 10,
        'rating' => 4,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2026-07-20',
    ],
    [
        'user_id' => 61,
        'book_id' => 21,
        'rating' => 2,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2026-08-01',
    ],
    [
        'user_id' => 62,
        'book_id' => 32,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2026-08-15',
    ],
    [
        'user_id' => 63,
        'book_id' => 43,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2026-09-01',
    ],
    [
        'user_id' => 64,
        'book_id' => 44,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2026-09-20',
    ],
    [
        'user_id' => 65,
        'book_id' => 35,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2026-10-05',
    ],
    [
        'user_id' => 66,
        'book_id' => 26,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2026-10-20',
    ],
    [
        'user_id' => 67,
        'book_id' => 17,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2026-11-01',
    ],
    [
        'user_id' => 17,
        'book_id' => 17,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2026-11-15',
    ],
    [
        'user_id' => 19,
        'book_id' => 19,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2026-12-01',
    ],
    [
        'user_id' => 17,
        'book_id' => 17,
        'rating' => 3,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2026-12-20',
    ],
    [
        'user_id' => 14,
        'book_id' => 14,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2027-01-05',
    ],
    [
        'user_id' => 8,
        'book_id' => 8,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2027-01-20',
    ],
    [
        'user_id' => 36,
        'book_id' => 36,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2027-02-01',
    ],
    [
        'user_id' => 22,
        'book_id' => 22,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2027-02-15',
    ],
    [
        'user_id' => 30,
        'book_id' => 30,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2027-03-01',
    ],
    [
        'user_id' => 33,
        'book_id' => 33,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2027-03-20',
    ],
    [
        'user_id' => 11,
        'book_id' => 11,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2027-04-05',
    ],
    [
        'user_id' => 5,
        'book_id' => 5,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2027-04-20',
    ],
    [
        'user_id' => 7,
        'book_id' => 7,
        'rating' => 2,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2027-05-01',
    ],
    [
        'user_id' => 7,
        'book_id' => 7,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2027-05-15',
    ],
    [
        'user_id' => 7,
        'book_id' => 7,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2027-06-01',
    ],
    [
        'user_id' => 39,
        'book_id' => 39,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2027-06-20',
    ],
    [
        'user_id' => 37,
        'book_id' => 37,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2027-07-05',
    ],
    [
        'user_id' => 23,
        'book_id' => 23,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2027-07-20',
    ],
    [
        'user_id' => 42,
        'book_id' => 42,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2027-08-01',
    ],
    [
        'user_id' => 4,
        'book_id' => 4,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2027-08-15',
    ],
    [
        'user_id' => 28,
        'book_id' => 28,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2027-09-01',
    ],
    [
        'user_id' => 26,
        'book_id' => 26,
        'rating' => 3,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2027-09-20',
    ],
    [
        'user_id' => 9,
        'book_id' => 9,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2027-10-05',
    ],
    [
        'user_id' => 10,
        'book_id' => 10,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2027-10-20',
    ],
    [
        'user_id' => 31,
        'book_id' => 31,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2027-11-01',
    ],
    [
        'user_id' => 21,
        'book_id' => 21,
        'rating' => 5,
        'comment' => 'Một trong những cuốn sách hay nhất tôi từng đọc!',
        'date_review' => '2027-11-15',
    ],
    [
        'user_id' => 53,
        'book_id' => 13,
        'rating' => 3,
        'comment' => 'Nội dung ổn nhưng cần thêm phần thực hành.',
        'date_review' => '2027-12-01',
    ],
    [
        'user_id' => 4,
        'book_id' => 14,
        'rating' => 4,
        'comment' => 'Rất thích phần phân tích sâu sắc của tác giả.',
        'date_review' => '2027-12-20',
    ],
    [
        'user_id' => 35,
        'book_id' => 25,
        'rating' => 5,
        'comment' => 'Một cuốn sách không thể bỏ qua cho những ai yêu thích thể loại này.',
        'date_review' => '2028-01-05',
    ],
    [
        'user_id' => 3,
        'book_id' => 43,
        'rating' => 4,
        'comment' => 'Tôi đã học được nhiều điều mới mẻ từ cuốn sách này.',
        'date_review' => '2028-01-20',
    ],
    [
        'user_id' => 7,
        'book_id' => 47,
        'rating' => 2,
        'comment' => 'Nội dung khá hay nhưng có vài phần hơi khó hiểu.',
        'date_review' => '2028-02-01',
    ],
    [
        'user_id' => 15,
        'book_id' => 18,
        'rating' => 5,
        'comment' => 'Một tác phẩm xuất sắc, tôi rất thích cách tác giả truyền đạt ý tưởng.',
        'date_review' => '2028-02-15',
    ],
    [
        'user_id' => 22,
        'book_id' => 34,
        'rating' => 4,
        'comment' => 'Rất đáng đọc, nội dung phong phú và sâu sắc.',
        'date_review' => '2028-03-01',
    ],
    [
        'user_id' => 11,
        'book_id' => 33,
        'rating' => 2,
        'comment' => 'Không như tôi mong đợi, hơi thất vọng.',
        'date_review' => '2028-03-20',
    ],  

]);

    }
}
