<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
         $users = [
            [
                'full_name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('123456'),
                'phone' => '0931234567',
                'address' => '123 Đường Láng, Quận Đống Đa, Hà Nội',
                'dob' => '1992-05-15',
                'role' => 'admin',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyen Van An',
                'email' => 'nguyenvanan@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0901234567',
                'address' => '123 Đường Láng, Quận Đống Đa, Hà Nội',
                'dob' => '1990-05-15',
                'role' => 'manager',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Tran Thi Bich',
                'email' => 'tranthibich@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0912345678',
                'address' => '456 Phố Huế, Quận Hai Bà Trưng, Hà Nội',
                'dob' => '1985-08-22',
                'role' => 'manager',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Le Van Cuong',
                'email' => 'levancuong@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0923456789',
                'address' => '789 Đường Giải Phóng, Quận Hoàng Mai, Hà Nội',
                'dob' => '1995-03-10',
                'role' => 'admin',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
         
            // 
            [
                'full_name' => 'Nguyễn Văn An',
                'email' => 'nguyenvanan' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0934' . rand(100000, 999999),
                'address' => '123 Lê Lợi, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1990-05-15',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Thị Bích',
                'email' => 'tranthibich' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0912' . rand(100000, 999999),
                'address' => '45 Nguyễn Huệ, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1985-08-22',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lê Minh Châu',
                'email' => 'leminhchau' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0987' . rand(100000, 999999),
                'address' => '78 Trần Phú, Quận Hải Châu, Đà Nẵng',
                'dob' => '1995-03-10',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phạm Quốc Đạt',
                'email' => 'phamquocdat' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0905' . rand(100000, 999999),
                'address' => '56 Phạm Văn Đồng, Quận Cầu Giấy, Hà Nội',
                'dob' => '1987-12-01',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Hoàng Thị Ngọc',
                'email' => 'hoangthingoc' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0943' . rand(100000, 999999),
                'address' => '101 Lý Thường Kiệt, Quận Tân Bình, TP. Hồ Chí Minh',
                'dob' => '1992-07-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Mai',
                'email' => 'nguyenthimai' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0932' . rand(100000, 999999),
                'address' => '34 Nguyễn Trãi, Quận Thanh Xuân, Hà Nội',
                'dob' => '1993-04-15',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Văn Hùng',
                'email' => 'tranvanhung' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0912' . rand(100000, 999999),
                'address' => '89 Lê Duẩn, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1988-09-10',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phạm Văn Nam',
                'email' => 'phamvannam' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0945' . rand(100000, 999999),
                'address' => '67 Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1991-11-25',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Lan',
                'email' => 'nguyenthilan' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0936' . rand(100000, 999999),
                'address' => '12 Nguyễn Văn Cừ, Quận Long Biên, Hà Nội',
                'dob' => '1994-06-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Bình',
                'email' => 'nguyenvanbinh' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0901' . rand(100000, 999999),
                'address' => '23 Lê Lai, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1990-02-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Thị Hoa',
                'email' => 'tranthihoa' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0913' . rand(100000, 999999),
                'address' => '45 Nguyễn Thị Minh Khai, Quận 3, TP. Hồ Chí Minh',
                'dob' => '1992-08-15',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Tài',
                'email' => 'nguyenvantai' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0938' . rand(100000, 999999),
                'address' => '78 Trần Quốc Toản, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1995-01-05',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Hương',
                'email' => 'nguyenthihuong' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0942' . rand(100000, 999999),
                'address' => '34 Lê Văn Sỹ, Quận Phú Nhuận, TP. Hồ Chí Minh',
                'dob' => '1993-10-10',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Khải',
                'email' => 'nguyenvankhai' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0902' . rand(100000, 999999),
                'address' => '56 Nguyễn Thị Minh Khai, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1991-12-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Lan',
                'email' => 'nguyenthilan' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0936' . rand(100000, 999999),
                'address' => '12 Nguyễn Văn Cừ, Quận Long Biên, Hà Nội',
                'dob' => '1994-06-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Phúc',
                'email' => 'nguyenvanphuc' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0903' . rand(100000, 999999),
                'address' => '67 Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1990-03-15',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Dũng',
                'email' => 'nguyenvandung' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0934' . rand(100000, 999999),
                'address' => '101 Nguyễn Trãi, Quận Thanh Xuân, Hà Nội',
                'dob' => '1988-11-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Hằng',
                'email' => 'nguyenthihang' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0941' . rand(100000, 999999),
                'address' => '23 Lê Lai, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1992-02-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Hòa',
                'email' => 'nguyenvanhoaa' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0904' . rand(100000, 999999),
                'address' => '45 Nguyễn Thị Minh Khai, Quận 3, TP. Hồ Chí Minh',
                'dob' => '1995-05-25',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Tâm',
                'email' => 'nguyenvantam' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0935' . rand(100000, 999999),
                'address' => '78 Trần Quốc Toản, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1993-01-05',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Khoa',
                'email' => 'nguyenvankhoa' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0940' . rand(100000, 999999),
                'address' => '34 Lê Văn Sỹ, Quận Phú Nhuận, TP. Hồ Chí Minh',
                'dob' => '1994-10-10',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Quang',
                'email' => 'nguyenvanquang' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0906' . rand(100000, 999999),
                'address' => '56 Nguyễn Thị Minh Khai, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1991-12-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Huy',
                'email' => 'nguyenvanhuy' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0937' . rand(100000, 999999),
                'address' => '12 Nguyễn Văn Cừ, Quận Long Biên, Hà Nội',
                'dob' => '1990-06-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Phương',
                'email' => 'nguyenvanphuong' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0908' . rand(100000, 999999),
                'address' => '67 Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1992-03-15',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Sơn',
                'email' => 'nguyenvanson' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0939' . rand(100000, 999999),
                'address' => '101 Nguyễn Trãi, Quận Thanh Xuân, Hà Nội',
                'dob' => '1988-11-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Kiên',
                'email' => 'nguyenvankien' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0943' . rand(100000, 999999),
                'address' => '23 Lê Lai, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1995-02-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Thắng',
                'email' => 'nguyenvanthang' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0909' . rand(100000, 999999),
                'address' => '45 Nguyễn Thị Minh Khai, Quận 3, TP. Hồ Chí Minh',
                'dob' => '1993-05-25',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Đức',
                'email' => 'nguyenvanduc' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0931' . rand(100000, 999999),
                'address' => '78 Trần Quốc Toản, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1994-01-05',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Lộc',
                'email' => 'nguyenvanloc' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0944' . rand(100000, 999999),
                'address' => '34 Lê Văn Sỹ, Quận Phú Nhuận, TP. Hồ Chí Minh',
                'dob' => '1990-10-10',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Hòa',
                'email' => 'nguyenvanhoaa' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0932' . rand(100000, 999999),
                'address' => '12 Nguyễn Văn Cừ, Quận Long Biên, Hà Nội',
                'dob' => '1995-06-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Hải',
                'email' => 'nguyenvanhai' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0905' . rand(100000, 999999),
                'address' => '67 Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1991-12-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Phát',
                'email' => 'nguyenvanphat' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0933' . rand(100000, 999999),
                'address' => '101 Nguyễn Trãi, Quận Thanh Xuân, Hà Nội',
                'dob' => '1989-11-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Tài',
                'email' => 'nguyenvantai' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0946' . rand(100000, 999999),
                'address' => '23 Lê Lai, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1992-02-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Thịnh',
                'email' => 'nguyenvanthinh' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0907' . rand(100000, 999999),
                'address' => '45 Nguyễn Thị Minh Khai, Quận 3, TP. Hồ Chí Minh',
                'dob' => '1993-05-25',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Quý',
                'email' => 'nguyenvanquy' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0930' . rand(100000, 999999),
                'address' => '78 Trần Quốc Toản, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1994-01-05',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Cường',
                'email' => 'nguyenvancuong' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0945' . rand(100000, 999999),
                'address' => '34 Lê Văn Sỹ, Quận Phú Nhuận, TP. Hồ Chí Minh',
                'dob' => '1990-10-10',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Duy',
                'email' => 'nguyenvanduy' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0938' . rand(100000, 999999),
                'address' => '12 Nguyễn Văn Cừ, Quận Long Biên, Hà Nội',
                'dob' => '1995-06-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Đỗ Thị Hồng',
                'email' => 'dothihong' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0978' . rand(100000, 999999),
                'address' => '234 Hai Bà Trưng, Quận 3, TP. Hồ Chí Minh',
                'dob' => '1993-04-17',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Vũ Minh Tuấn',
                'email' => 'vuminhtuan' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0915' . rand(100000, 999999),
                'address' => '67 Đinh Tiên Hoàng, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1989-09-25',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Lan',
                'email' => 'nguyenthilan' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0932' . rand(100000, 999999),
                'address' => '89 Lý Nam Đế, Quận Ba Đình, Hà Nội',
                'dob' => '1991-11-03',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Quốc Hùng',
                'email' => 'tranquochung' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0963' . rand(100000, 999999),
                'address' => '12 Nguyễn Văn Cừ, Quận Long Biên, Hà Nội',
                'dob' => '1986-06-12',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lê Thị Mai',
                'email' => 'lethimai' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0947' . rand(100000, 999999),
                'address' => '45 Võ Văn Tần, Quận 3, TP. Hồ Chí Minh',
                'dob' => '1994-02-28',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phạm Văn Khôi',
                'email' => 'phamvankhoi' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0921' . rand(100000, 999999),
                'address' => '78 Hùng Vương, TP. Huế, Thừa Thiên Huế',
                'dob' => '1990-10-19',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Hoàng Minh Thư',
                'email' => 'hoangminhthu' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0989' . rand(100000, 999999),
                'address' => '56 Lê Đại Hành, Quận Hai Bà Trưng, Hà Nội',
                'dob' => '1988-12-07',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ngô Thị Hà',
                'email' => 'ngothiha' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0903' . rand(100000, 999999),
                'address' => '123 Trần Hưng Đạo, Quận 5, TP. Hồ Chí Minh',
                'dob' => '1996-03-14',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Bùi Văn Nam',
                'email' => 'buivannam' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0938' . rand(100000, 999999),
                'address' => '34 Nguyễn Đình Chiểu, Quận Phú Nhuận, TP. Hồ Chí Minh',
                'dob' => '1987-07-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Đặng Thị Ngọc Ánh',
                'email' => 'dangthingocanh' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0919' . rand(100000, 999999),
                'address' => '67 Lê Lợi, TP. Nha Trang, Khánh Hòa',
                'dob' => '1993-01-05',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trương Văn Hào',
                'email' => 'truongvanhao' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0965' . rand(100000, 999999),
                'address' => '89 Nguyễn Thị Minh Khai, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1992-09-08',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lý Thị Thanh',
                'email' => 'lythithanh' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0937' . rand(100000, 999999),
                'address' => '123 Phạm Ngũ Lão, Quận Hải Châu, Đà Nẵng',
                'dob' => '1989-02-14',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Quốc Anh',
                'email' => 'nguyenquocanh' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0913' . rand(100000, 999999),
                'address' => '45 Kim Mã, Quận Ba Đình, Hà Nội',
                'dob' => '1995-06-22',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phan Thị Hồng Nhung',
                'email' => 'phanthihongnhung' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0942' . rand(100000, 999999),
                'address' => '78 Lê Duẩn, TP. Vinh, Nghệ An',
                'dob' => '1990-11-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Võ Minh Nhật',
                'email' => 'vominhnhat' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0973' . rand(100000, 999999),
                'address' => '56 Nguyễn Văn Trỗi, Quận Phú Nhuận, TP. Hồ Chí Minh',
                'dob' => '1987-03-19',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Đinh Thị Lan Anh',
                'email' => 'dinhthilananh' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0982' . rand(100000, 999999),
                'address' => '101 Lê Lợi, TP. Huế, Thừa Thiên Huế',
                'dob' => '1994-08-05',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Hà Văn Long',
                'email' => 'havanlong' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0907' . rand(100000, 999999),
                'address' => '34 Trần Phú, Quận Ngô Quyền, Hải Phòng',
                'dob' => '1988-05-12',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Bùi Thị Minh Thư',
                'email' => 'buithiminhthu' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0927' . rand(100000, 999999),
                'address' => '67 Nguyễn Huệ, TP. Quy Nhơn, Bình Định',
                'dob' => '1993-12-25',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lương Văn Khánh',
                'email' => 'luongvankhanh' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0968' . rand(100000, 999999),
                'address' => '123 Hoàng Diệu, Quận Thanh Khê, Đà Nẵng',
                'dob' => '1991-07-03',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ngô Thị Phương',
                'email' => 'ngothiphuong' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0931' . rand(100000, 999999),
                'address' => '45 Lý Thường Kiệt, Quận Tân Bình, TP. Hồ Chí Minh',
                'dob' => '1986-10-15',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Hưng',
                'email' => 'nguyenvanhung' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0946' . rand(100000, 999999),
                'address' => '78 Trần Quốc Toản, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1992-04-20',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Văn Dũng',
                'email' => 'tranvandung' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0908' . rand(100000, 999999),
                'address' => '101 Nguyễn Trãi, Quận Thanh Xuân, Hà Nội',
                'dob' => '1995-08-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Mai',
                'email' => 'nguyenthimai' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0934' . rand(100000, 999999),
                'address' => '34 Lê Văn Sỹ, Quận Phú Nhuận, TP. Hồ Chí Minh',
                'dob' => '1990-01-10',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phạm Văn An',
                'email' => 'phamvanan' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0948' . rand(100000, 999999),
                'address' => '12 Nguyễn Văn Cừ, Quận Long Biên, Hà Nội',
                'dob' => '1993-02-22',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Tùng',
                'email' => 'nguyenvantung' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0902' . rand(100000, 999999),
                'address' => '67 Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội',
                'dob' => '1991-03-15',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Bình',
                'email' => 'nguyenvanbinh' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0935' . rand(100000, 999999),
                'address' => '101 Nguyễn Trãi, Quận Thanh Xuân, Hà Nội',
                'dob' => '1989-11-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Lâm',
                'email' => 'nguyenvanlam' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0940' . rand(100000, 999999),
                'address' => '23 Lê Lai, Quận 1, TP. Hồ Chí Minh',
                'dob' => '1994-05-25',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Hòa',
                'email' => 'nguyenvanhoaa' . rand(100, 999) . '@gmail.com',
                'password' => Hash::make('1234567'),
                'phone' => '0936' . rand(100000, 999999),
                'address' => '45 Nguyễn Thị Minh Khai, Quận 3, TP. Hồ Chí Minh',
                'dob' => '1992-06-30',
                'role' => 'user',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        // Chèn tất cả người dùng vào bảng users
        foreach ($users as $user) {
            DB::table('users')->insert($user);
        }
    }
}